relations:
  - relation: PART_OF
    source:
      apiVersion: entities.devgraph.ai/v1
      kind: GithubRepository
      name: devgraph-cli
    target:
      apiVersion: meta.devgraph.ai/v1
      kind: Project
      name: devgraph
