linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocritic
    - unconvert

linters-settings:
  gosec:
    tests: true
    
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocritic:
    enabled-tags:
      - security
      - diagnostic

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0