version: "2"
linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gocritic
    - unconvert

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
