version: "2"
linters:
  enable:
    - govet
    - ineffassign
    - unused
    - misspell
  disable:
    - errcheck
    - gosec
    - gocritic
    - unconvert
    - staticcheck

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
