# .goreleaser.yaml
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    binary: "{{ .Env.CLI_NAME }}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
  - format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    builds:
      - windows_amd64
    files:
      - README.md

release:
  github:
    owner: "{{ .Owner }}"
    name: "{{ .Repo }}"

changelog:
  disable: false # Replaced 'skip' with 'disable'
  use: github